version: "3"

services:
  printscript-service:
    container_name: "printscript-service"
    image: ghcr.io/tps-ingenieria-de-sistemas/printscript-service:latest
    ports:
      - "8080:8080"

  snippet-permits:
    container_name: "snippet-permits"
    image: ghcr.io/tps-ingenieria-de-sistemas/snippet-permits:latest
    ports:
      - "8081:8081"

  snippet-service:
    container_name: "snippet-service"
    image: ghcr.io/tps-ingenieria-de-sistemas/snippet-service:latest
    ports:
      - "8082:8082"

  asset-service:
    container_name: "asset-service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8083:8083"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - printscript_service
      - snippet_permits
      - snippet_service
      - asset_service

  duckdns:
    image: lscr.io/linuxserver/duckdns:version-9fc9520a
    container_name: duckdns
    environment:
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped


volumes:
  blob:
    external: false
