version: "3"

services:
  printscript_service:
    container_name: "printscript_service"
    image: ghcr.io/tps-ingenieria-de-sistemas/printscript-service:latest
    ports:
      - "8080:8080"

  snippet_permits:
    container_name: "snippet_permits"
    image: ghcr.io/tps-ingenieria-de-sistemas/snippet-permits:latest
    ports:
      - "8081:8080"

  snippet_service:
    container_name: "snippet_service"
    image: ghcr.io/tps-ingenieria-de-sistemas/snippet-service:latest
    ports:
      - "8082:8080"

  asset_service:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8083:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  blob:
    external: false
