name: UPDATE DEV SERVER WITH NEW INFRA

on:
  push:
    branches:
      - dev

jobs:
  connect-and-update-infra:
    runs-on: ubuntu-latest
    steps:
    - name: connect-and-run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_URL }}
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
        script: |
          cd infra
          git pull
          sudo docker compose down
          sudo docker compose up -d
